# Generated by Django 3.0.8 on 2020-07-13 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link_to_apply', models.URLField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], default='Full-time', max_length=9)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remote', models.BooleanField()),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='media/logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('fulfilled', models.BooleanField()),
                ('applicants', models.ManyToManyField(blank=True, related_name='my_applications', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
