# Generated by Django 3.0.8 on 2020-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
