# Generated by Django 3.0.8 on 2020-07-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200714_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='job',
            name='company_website',
            field=models.URLField(max_length=255),
        ),
    ]
